@startuml Parcel tracking system with Controllers
title Система автоматизации учета и отслеживания посылок в логистических компаниях

actor Пользователь as Client
boundary "Интерфейс пользователя" as ClientView
boundary "Интерфейс оператора" as OperatorView
actor Оператор as Operator
control "Контроллер поиска посылки" as FindParcelController
control "Контроллер добавления посылки" as AddParcelController
control "Контроллер изменения посылки" as ChangeStatusController
database "База данных посылок" as DB

Client -> ClientView : Поиск посылки по трек-индексу
ClientView -> FindParcelController : Найти посылку в систиме
FindParcelController -> DB : Запрос на поиск посылки
DB --> FindParcelController : Данные о статусе посылки
FindParcelController --> ClientView : Вывод описания и статуса посылки 

Operator -> OperatorView : Поиск посылки по трек-индексу
OperatorView -> FindParcelController : Найти посылку в систeме
FindParcelController -> DB : Запрос на поиск посылки
DB --> FindParcelController : Данные о статусе посылки
FindParcelController --> OperatorView : Вывод описания и статуса посылки 

Operator -> OperatorView : Создание описания посылки
OperatorView -> AddParcelController : Создать описание посылки в систиме
AddParcelController -> DB : Запрос на добавление посылки
DB --> AddParcelController : Добавление посылки
AddParcelController --> Operator : Посылка добавлена

Operator -> OperatorView : Изменение статуса посылки
OperatorView -> ChangeStatusController : Изменить статус посылки
ChangeStatusController -> DB : Запрос на изменение статуса
DB --> ChangeStatusController : Изменение статуса посылки
ChangeStatusController --> Operator : Статус изменен

@enduml
